Update cape2.sh
added ninja-build to dependencies, required for pyre2 build.

 error: subprocess-exited-with-error
  
  × Building wheel for pyre2 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      running bdist_wheel
      running build
      running build_ext
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.